"""add movstock and totales

Revision ID: 1c90fa2bc07d
Revises: b88d80214646
Create Date: 2026-08-15 14:19:48.967180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c90fa2bc07d'
down_revision: Union[str, Sequence[str], None] = 'b88d80214646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MovStock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('COD1', sa.String(length=5), nullable=True),
    sa.Column('COD2', sa.String(length=10), nullable=True),
    sa.Column('FECHA', sa.Date(), nullable=True),
    sa.Column('TIPO', sa.String(length=2), nullable=True),
    sa.Column('PTOVTA', sa.Integer(), nullable=True),
    sa.Column('CPBTE', sa.Integer(), nullable=True),
    sa.Column('ITEM', sa.Integer(), nullable=True),
    sa.Column('PULG', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('MTR', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('MILIM', sa.Integer(), nullable=True),
    sa.Column('TELAS', sa.Integer(), nullable=True),
    sa.Column('CANT', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('USUARIO', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Totales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FECHA', sa.Date(), nullable=True),
    sa.Column('FACA', sa.Integer(), nullable=True),
    sa.Column('FACB', sa.Integer(), nullable=True),
    sa.Column('FACC', sa.Integer(), nullable=True),
    sa.Column('NCA', sa.Integer(), nullable=True),
    sa.Column('NCB', sa.Integer(), nullable=True),
    sa.Column('NCC', sa.Integer(), nullable=True),
    sa.Column('NDA', sa.Integer(), nullable=True),
    sa.Column('NDB', sa.Integer(), nullable=True),
    sa.Column('NDC', sa.Integer(), nullable=True),
    sa.Column('MOSTA', sa.Integer(), nullable=True),
    sa.Column('MOSTB', sa.Integer(), nullable=True),
    sa.Column('MOSTC', sa.Integer(), nullable=True),
    sa.Column('NCMOSTA', sa.Integer(), nullable=True),
    sa.Column('NCMOSTB', sa.Integer(), nullable=True),
    sa.Column('NCMOSTC', sa.Integer(), nullable=True),
    sa.Column('UNIDA', sa.Integer(), nullable=True),
    sa.Column('UNIDB', sa.Integer(), nullable=True),
    sa.Column('UNIDC', sa.Integer(), nullable=True),
    sa.Column('DEV', sa.Integer(), nullable=True),
    sa.Column('MOSTDEV', sa.Integer(), nullable=True),
    sa.Column('UNMOSTA', sa.Integer(), nullable=True),
    sa.Column('UNMOSTB', sa.Integer(), nullable=True),
    sa.Column('UNMOSTC', sa.Integer(), nullable=True),
    sa.Column('PVTA', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('PCOS', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('PESP', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('PESPA', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('PESPB', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('PESPC', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('PESPMOSTA', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('PESPMOSTB', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('PESPMOSTC', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('EXPA', sa.Integer(), nullable=True),
    sa.Column('EXPB', sa.Integer(), nullable=True),
    sa.Column('NCEXPA', sa.Integer(), nullable=True),
    sa.Column('NCEXPB', sa.Integer(), nullable=True),
    sa.Column('PESPEXPA', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('PESPEXPB', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('UNEXPA', sa.Integer(), nullable=True),
    sa.Column('UNEXPB', sa.Integer(), nullable=True),
    sa.Column('UNEXPC', sa.Integer(), nullable=True),
    sa.Column('EXPDEV', sa.Integer(), nullable=True),
    sa.Column('ACUCPRAS', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('USUARIO', sa.String(length=6), nullable=True),
    sa.Column('FACTUAL', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Totales')
    op.drop_table('MovStock')
    # ### end Alembic commands ###
