"""agrega tabla dtoxclte (descuentos por seccion y cliente)

Revision ID: 56c4222f3b26
Revises: aa584d0b6666
Create Date: 2026-08-15 11:38:26.610749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c4222f3b26'
down_revision: Union[str, Sequence[str], None] = 'aa584d0b6666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DtoxClte',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CLTE', sa.Integer(), nullable=False),
    sa.Column('SECCION', sa.String(length=5), nullable=True),
    sa.Column('DTO1', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('DTO2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('DTO3', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('DTO4', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('DTO5', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('RGO1', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('RGO2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('RGO3', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('USUARIO', sa.String(length=20), nullable=True),
    sa.Column('FACTUAL', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DtoxClte')
    # ### end Alembic commands ###
