"""corrige tipos TIPO y TIPREG de MovimVS a texto

Revision ID: 8cd556285914
Revises: c5d3a39ce576
Create Date: 2026-08-15 20:00:05.575301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd556285914'
down_revision: Union[str, Sequence[str], None] = 'c5d3a39ce576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MovimVS', 'TIPO',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.alter_column('MovimVS', 'TIPREG',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MovimVS', 'TIPREG',
               existing_type=sa.String(length=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('MovimVS', 'TIPO',
               existing_type=sa.String(length=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
