"""agrega tabla notartic (notas de articulo)

Revision ID: aa584d0b6666
Revises: 476bdfaf3277
Create Date: 2026-08-15 11:24:29.559944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa584d0b6666'
down_revision: Union[str, Sequence[str], None] = '476bdfaf3277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notartic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('COD1', sa.String(length=30), nullable=True),
    sa.Column('COD2', sa.String(length=30), nullable=True),
    sa.Column('TITULO1', sa.Text(), nullable=True),
    sa.Column('NOTA1', sa.Text(), nullable=True),
    sa.Column('PIE1', sa.Text(), nullable=True),
    sa.Column('TITULO2', sa.Text(), nullable=True),
    sa.Column('NOTA2', sa.Text(), nullable=True),
    sa.Column('PIE2', sa.Text(), nullable=True),
    sa.Column('TITULO3', sa.Text(), nullable=True),
    sa.Column('NOTA3', sa.Text(), nullable=True),
    sa.Column('PIE3', sa.Text(), nullable=True),
    sa.Column('TITULO4', sa.Text(), nullable=True),
    sa.Column('NOTA4', sa.Text(), nullable=True),
    sa.Column('PIE4', sa.Text(), nullable=True),
    sa.Column('TITULO5', sa.Text(), nullable=True),
    sa.Column('NOTA5', sa.Text(), nullable=True),
    sa.Column('PIE5', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Notartic')
    # ### end Alembic commands ###
