"""agrega tabla Despachos

Revision ID: b88d80214646
Revises: 56c4222f3b26
Create Date: 2026-08-15 12:50:22.489925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88d80214646'
down_revision: Union[str, Sequence[str], None] = '56c4222f3b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Despachos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('COD1', sa.String(length=5), nullable=True),
    sa.Column('COD2', sa.String(length=10), nullable=True),
    sa.Column('NRODESP', sa.String(length=20), nullable=True),
    sa.Column('CPBTE', sa.Integer(), nullable=True),
    sa.Column('ENTRADA', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('SALIDAS', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('STOCK', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('FECENT', sa.Date(), nullable=True),
    sa.Column('FECUSAL', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Despachos')
    # ### end Alembic commands ###
