"""agrega tablas Efectivo y MovimVS

Revision ID: c5d3a39ce576
Revises: 1c90fa2bc07d
Create Date: 2026-08-15 19:56:59.183490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d3a39ce576'
down_revision: Union[str, Sequence[str], None] = '1c90fa2bc07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Efectivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FECHA', sa.Date(), nullable=True),
    sa.Column('TIPO', sa.Integer(), nullable=True),
    sa.Column('CPBTE', sa.Integer(), nullable=True),
    sa.Column('IMPTE', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MovimVS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CLTE', sa.Integer(), nullable=True),
    sa.Column('FECHA', sa.Date(), nullable=True),
    sa.Column('TIPO', sa.Integer(), nullable=True),
    sa.Column('CPBTE', sa.Integer(), nullable=True),
    sa.Column('TIPREG', sa.Integer(), nullable=True),
    sa.Column('IMPTE', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('BCOSUC', sa.String(length=6), nullable=True),
    sa.Column('DATOSAD', sa.String(length=50), nullable=True),
    sa.Column('CONCEP', sa.String(length=50), nullable=True),
    sa.Column('OBSERV', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MovimVS')
    op.drop_table('Efectivo')
    # ### end Alembic commands ###
